name: Chris Ahern Photography
favicon: null
layout_spectrum: 0.5730414623394608
typography_spectrum: 0.08397134835831821
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5274433037266135
  lightness: 0.848707421682775
  saturation: 0.3297340767458081
  rhythmicContrast: 0.34126677620224655
purpose: []
